windows:
  hosts:
  children:
    windows_dc:
      hosts:
        192.168.7.75:
          hostname: dc-blue1
    windows_wks:
      hosts:

  vars:
    ansible_user: deployer
    ansible_shell_type: powershell
    shell_type: powershell
    domain: "blue1"
    domain_name: "{{ domain }}.local"
    domain_admin_user: "Administrator"
    password_length: 16
    password_special_chars: true
