#usage: ansible-playbook -i inventories/windows.yaml --ask-pass windows_ad_groups_users.yml -K
- name: Create Users and Groups
  hosts: windows_dc

  vars_prompt:
    - name: domain_admin_pass
      prompt: "Enter your domain admin password"

  tasks:
    - name: Read CSV File
      read_csv:
        path: "{{ csv_path }}"
        key: name
      register: users
      delegate_to: 127.0.0.1
      vars:
        ansible_shell_type:

    - name: Generate Random Passwords Part 1
      set_fact:
        users_dict: "{{ users.dict }}"
    
    - name: Generate Random Password Part 2
      set_fact:
        users_dict: "{{ users_dict | combine(new_item, recursive=true) }}"
      vars:
        new_item: "{ '{{ item.key }}': { 'password': '{{ lookup('password', '/dev/null', chars='ascii_letters,digits', length=16) }}' } }"
      with_dict: "{{ users_dict }}"
    
    - name: Make new list
      set_fact:
        users: "{{ users_dict.values() | list }}"

    - name: Create Group
      win_domain_group:
        domain_username: "{{ ansible_user }}"
        domain_password: "{{ domain_admin_pass }}"
        name: "{{ item.group }}"
        path: "OU=Groups,OU=Accounts,OU=Blue1,DC={{ domain }},DC=local"
        state: present
        scope: global
      loop: "{{ users }}"

    - name: Create User
      win_domain_user:
        domain_username: "{{ ansible_user }}"
        domain_password: "{{ domain_admin_pass }}"
        name: "{{ item.name }}"
        groups: "{{ item.group }}, Domain Users"
        password: "{{ item.password }}"
        path: "OU=Accounts,OU=Blue1,DC={{ domain }},DC=local"
        password_never_expires: true
        state: present
      loop: "{{ users }}"
    
    - name: Print User Info
      debug:
        msg: "Username: {{ item.name }} Password: {{ item.password }}"
      loop: "{{ users }}"
