#usage: ansible-playbook -i inventories/windows.yaml --ask-pass windows_ad_groups_users.yml -K
- name: Create Users and Groups
  hosts: windows_dc

  vars_prompt:
    - name: domain_admin_pass
      prompt: "Enter your domain admin password"

  tasks:
    - name: Read CSV File
      read_csv:
        path: "{{ csv_path }}"
      register: users
      delegate_to: 127.0.0.1
      vars:
        ansible_shell_type:
    
    - name: An Ansible Loop
      debug:
        msg: "{{ item.name }} - {{ item.group }}"
      with_items: "{{ users.list }}"

    - name: Generate Random password
      set_fact:
        users: "{{ users.list | map('combine', {'password': lookup('password', '/dev/null length=14 chars=ascii_letters,digits')}) | list }}"

    - name: Create Group
      win_domain_group:
        domain_username: "{{ ansible_user }}"
        domain_password: "{{ domain_admin_pass }}"
        name: "{{ item.group }}"
        path: "OU=Groups,OU=Accounts,OU=Blue1,DC={{ domain }},DC=local"
        state: present
        scope: global
      loop: "{{ users }}"

    - name: Create User
      win_domain_user:
        domain_username: "{{ ansible_user }}"
        domain_password: "{{ domain_admin_pass }}"
        name: "{{ item.name }}"
        groups: "{{ item.group }}, Domain Users"
        password: "{{ item.password }}"
        path: "OU=Accounts,OU=Blue1,DC={{ domain }},DC=local"
        password_never_expires: true
        state: present
      loop: "{{ users }}"
    
    # - name: Add User to correct group
    #   win_shell: |
    #     Add-ADGroupMember -Identity "{{ item.group }}" -Members "{{ item.name }}"
    #   loop: "{{ users.list }}"
    #   when: item.group is defined
    #   become_method: runas
    #   become_user: "{{ domain_admin_user }}"
    
    - name: Print User Info
      debug:
        msg: "Username: {{ item.name }} Password: {{ item.password }}"
      loop: "{{ users }}"