#usage: ansible-playbook -i inventories/windows.yaml --ask-pass windows-ad-setup.yml -K
- name: Set local administrator password and hostname, create new forest, and create OU structure
  hosts: windows

  vars_prompt:
    - name: local_admin_pass
      prompt: "Enter your local admin password"

    - name: domain_admin_password
      prompt: "Enter your domain admin password"

  tasks:
    - name: Set local administrator password
      win_user:
        name: Administrator
        password: "{{ local_admin_pass }}"
        
    - name: Set hostname
      win_hostname:
        name: "{{ hostname }}"

    - name: Restart
      win_reboot:
        reboot_timeout_sec: 300
        msg: Restarting Machine!!
        post_reboot_delay: 30

    - name: Install AD
      win_feature:
        name: AD-Domain-Services
        state: present

    - name: Create new forest
      win_domain:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_admin_user }}@{{ domain_name }}"
        domain_admin_password: "{{ domain_admin_password }}"
        safe_mode_password: "{{ local_admin_pass }}"
        state: domain
      register: domain_created

    - name: Reboot if needed
      win_reboot:
        reboot_timeout_sec: 600
        post_reboot_delay: 30
      when: domain_created.reboot_required

    - name: Create OUs
      win_shell: |
        New-ADOrganizationalUnit -Name "Blue1" -Path "DC={{ domain }},DC=local"
        New-ADOrganizationalUnit -Name "Accounts" -Path "OU=Blue1,DC={{ domain }},DC=local"
        New-ADOrganizationalUnit -Name "Groups" -Path "OU=Accounts,OU=Blue1,DC={{ domain }},DC=local"
        New-ADOrganizationalUnit -Name "Computers" -Path "OU=Blue1,DC={{ domain }},DC=local"
        New-ADOrganizationalUnit -Name "Servers" -Path "OU=Computers,OU=Blue1,DC={{ domain }},DC=local"
        New-ADOrganizationalUnit -Name "Workstations" -Path "OU=Computers,OU=Blue1,DC={{ domain }},DC=local"

    - name: Add ansible user account to domain admins group
      win_shell: |
        Add-ADGroupMember -Identity "Domain Admins" -Members "{{ ansible_user }}"
      become_method: runas
      become_user: "{{ domain_admin_user }}"
