- name: Set local administrator password and hostname, create new forest, and create OU structure
  hosts: windows_servers

  vars_prompt:
    - name: local_admin_pass
      prompt: "Enter your local admin password"

    - name: domain_name
      prompt: "Enter your domain name"

    - name: domain_admin_user
      prompt: "Enter your domain admin username"

    - name: domain_admin_password
      prompt: "Enter your domain admin password"

  tasks:
    - name: Set local administrator password
      win_user:
        name: Administrator
        password: "{{ local_admin_pass }}"

    - name: Set hostname
      win_hostname:
        name: "{{ hostname }}.{{ domain_name }}"
        restart: yes

    - name: Create new forest
      win_domain:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_admin_user }}@{{ domain_name }}"
        domain_admin_password: "{{ domain_admin_password }}"
        safe_mode_password: "{{ local_admin_pass }}"
        state: domain
      register: domain_created

    - name: Create OU structure
      win_domain_ou:
        domain_username: "{{ domain_admin_username }}"
        domain_password: "{{ domain_admin_password }}"
        name: "{{ item.name }}"
        parent: "{{ item.parent }}"
        description: "{{ item.description }}"
      loop: "{{ ou_structure }}"
    
    - name: Add local admin account to domain admins group
      win_domain_group_membership:
        name: "Domain Admins"
        members: "Administrator"
        state: present
        domain_username: "{{ domain_admin_username }}"
        domain_password: "{{ domain_admin_password }}"
        domain_server: "{{ hostname }}"
